error: Add FindGroupSafe that doesn't throw iExceptions
and change iException to use it. this prevents recursion inside
iException. otherwise, if iException throws due to a missing preference
file, it will recurse until stack is exhausted.